language: php
os:
  - linux
dist: xenial
arch:
  - arm64-graviton2
virt: lxd
group: edge
php:
  - 7.4
jdk:
  - oraclejdk8
services:
  - mysql
sudo: true
install:
- |
  if [[ $TRAVIS_CPU_ARCH == "arm64" ]]; then
    sudo bash -ec '
    echo -e '\''[mysqld]\\nskip-grant-tables'\'' >/etc/mysql/conf.d/grant.cnf
    systemctl restart mysql
    mysql -e "UPDATE mysql.user SET Grant_priv='\''Y'\'', Super_priv='\''Y'\'' WHERE User='\''root'\''; flush privileges;"
    rm /etc/mysql/conf.d/grant.cnf
    systemctl restart mysql'
   fi
before_script:
  - mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
  - composer self-update 2.0.14
  - php --version
  - sudo apt-get install -y php-common
  - sudo phpdismod -v php7.4 xdebug
script: 
  - chmod u+x test.sh
  - ./test.sh
  - source ~/.bashrc
  - echo $test