language: php
os:
  - linux
dist: xenial
arch:
  - arm64-graviton2
virt: lxd
group: edge
php:
  - "7.4"
jdk:
  - oraclejdk8
services:
  - mysql
sudo: true
before_script:
  - composer self-update 2.0.14
  - php --version
  - sudo apt-get install -y php-common
  - bash .mysql.sh
  - sudo phpdismod -v php7.4 xdebug
#  - sudo mysql -u root -e "CREATE DATABASE drupal; CREATE USER 'drupal'@'localhost' IDENTIFIED BY 'drupal'; GRANT ALL ON drupal.* TO 'drupal'@'localhost';"
script: true