language: php
os:
  - linux
dist: xenial
arch:
  - arm64-graviton2
virt: lxd
group: edge
php:
  - "7.4"
env:
  global:
    - COMPOSER_BIN: "$TRAVIS_BUILD_DIR/vendor/bin"
    - BLT_DIR: "$TRAVIS_BUILD_DIR/vendor/acquia/blt"
jdk:
  - oraclejdk8
services:
  - mysql
  - xvfb
before_install:
  - composer self-update 2.0.14
  - composer install --prefer-dist
  - phpenv config-rm xdebug.ini
script: true
