language: php
os:
  - linux
dist: focal
arch:
  - arm64-graviton2
virt: lxd
group: edge
php:
  - "7.4"
jdk:
  - oraclejdk8
services:
  - mysql
before_script:
  - composer self-update 2.0.14
  - php --version
  - sudo apt-get install -y php-common
  - sudo phpdismod -v php7.4 xdebug
  - mysql -e 'drop user if exists drupal@localhost;'
  - mysql -e 'create user drupal@localhost;'
  - mysql -e 'drop database if exists drupal;'
  - mysql -e 'create database drupal;'
  - mysql -e 'grant all on *.* to drupal@localhost;' || true
script: true