language: php
os:
  - linux
dist: focal
arch:
  - arm64-graviton2
virt: lxd
group: edge
php:
  - "7.4"
env:
  global:
    - COMPOSER_BIN: "$TRAVIS_BUILD_DIR/vendor/bin"
    - BLT_DIR: "$TRAVIS_BUILD_DIR/vendor/acquia/blt"
jdk:
  - oraclejdk8
services:
  - mysql
install:
  - sudo ./install-apache.sh
before_script:
  - composer self-update 2.0.14
  - php --version
  - sudo apt-get install -y php-common
  - sudo phpdismod -v php7.4 xdebug
  - sudo systemctl restart apache2
script: true
